---

# Main tasks file for rsync role

- name: Create /etc/rsyncd.conf
  copy:
    src: files/rsyncd.conf
    dest: /etc/rsyncd.conf
    mode: 0644
  tags: [configuration,rsync]

- name: Create /etc/rsyncd.secrets
  copy:
    src: files/rsyncd.secrets
    dest: /etc/rsyncd.secrets
    mode: 0600
  notify:
    - restart rsync
  tags: [configuration,rsync]
